name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.136.4/hugo_extended_0.136.4_linux-amd64.tar.gz'
          tar -C /tmp -zxvf /tmp/hugo.tar.gz hugo

      - name: Check Hugo version
        run: /tmp/hugo version

      - name: Build
        run: /tmp/hugo

      - name: List files in public directory
        run: ls -la public

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Clearing existing files in built-site..."
          rm -rf ${GITHUB_WORKSPACE}/built-site/*  # Clear existing files

          echo "Copying new files to built-site..."
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          
          # Navigate to the built-site directory
          cd ${GITHUB_WORKSPACE}/built-site

          # Check for changes to commit
          git add .
          git config user.name "raciod"
          git config user.email "rachidactivity@gmail.com"

          if ! git diff --cached --quiet; then
            echo "Committing changes..."
            git commit -m 'Updated site'
            echo "Pushing to gh-pages..."
            git push origin gh-pages || { echo 'Push failed' && exit 1; }
          else
            echo "No changes to commit"
          fi
