name: Publish to GH Pages

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Optional: Triggers on pull requests to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.136.4/hugo_extended_0.136.4_linux-amd64.tar.gz'
          tar -C /tmp -zxvf /tmp/hugo.tar.gz hugo
          sudo mv /tmp/hugo /usr/local/bin/

      - name: Check Hugo version
        run: hugo version

      - name: Build
        run: hugo --minify

      - name: List files in public directory
        run: ls -la public

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Clearing existing files in built-site..."
          rm -rf ${GITHUB_WORKSPACE}/built-site/*  # Clear existing files

          echo "Copying new files to built-site..."
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          
          # Navigate to the built-site directory
          cd ${GITHUB_WORKSPACE}/built-site

          # Check for changes to commit
          git add .
          git config user.name "raciod"
          git config user.email "rachidactivity@gmail.com"

          # Debug: show current status
          git status

          if ! git diff --cached --quiet; then
            echo "Committing changes..."
            git commit -m 'Updated site'
            echo "Pushing to gh-pages..."
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/raciod/raciod.github.io.git gh-pages || { echo 'Push failed' && exit 1; }
          else
            echo "No changes to commit"
          fi
