name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.136.4/hugo_extended_0.136.4_linux-amd64.tar.gz'
          tar -C /tmp -zxvf /tmp/hugo.tar.gz hugo

      - name: Check Hugo version
        run: /tmp/hugo version

      - name: Build
        run: /tmp/hugo

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'raciod'  # Replace with your GitHub username
          git config user.email 'rachidactivity@gmail.com'  # Replace with your email
          
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m 'Updated site'
            git push origin gh-pages  # Specify the branch explicitly
          else
            echo "No changes to commit"
          fi
